### PR TITLE
fixes, cleaup

### PR DESCRIPTION
**Pull request by ksimuk**

### CODE REVIEW

**Comment by ghost** [comment]
2 Challenges fail using given solution
2. 2. Addition
2. 3. A*(B + C/3)
challenge

Also page 1.1 missing content (re problem with case sensitivity)

**Comment by ksimuk** [comment]
fixes pushed

**Comment by ghost** [comment]
Challenge: 2. 3. A*(B + C/3)  fails using given solution

**Comment by ksimuk** [comment]
sorry missed it

**Comment by ghost** [comment]
:+1:

**Pull request merged**
